// extract-hamvention-svgbooth-to-booth.ts
//
// Tool: converts SvgBooth[] data into Booth[] TypeScript source.
//
// must change import and several hard coded variables at the bottom
//
// Usage ( edit with hamvention-2026-svgbooth-building-1-maxim-<date>.ts
//         run as a script );
//
//   npx tsx extract-hamvention-svgbooth-to-booth.ts > src/data/hamvention-2026-booth-<date>.ts
//
// The generated file is a static data module ready to be checked in.
// It exports `mapBooths: [string, Booth[]]` — the same shape used by
// the conferenceData loader in src/lib/conferenceData.ts.
//

import {
  HAMVENTION_2026_BUILDING_1_MAXIM_BOOTHS,
  SVG_URL,
  type SvgBooth,
} from "./hamvention-2026-svgbooth-building-1-maxim-20260305.ts";
import type { Booth } from "@/types/conference";

/**
 * Convert an array of SVG booth records into the Booth[] format used by the
 * Leaflet map overlay and the exhibitor data layer.
 *
 * @param svgBooths  Source data extracted from an SVG floor-plan.
 * @param locationZone  Human-readable zone label stored on every Booth record.
 */
export function convertSvgBoothsToBooth(
  svgBooths: SvgBooth[],
  locationZone: string,
): Booth[] {
  return svgBooths.map((b) => ({
    id: b.boothNum,
    coords: b.coords,
    locationZone,
  }));
}

// ── CLI entry-point ──────────────────────────────────────────────────────────
// When this file is executed directly (e.g. via `npx tsx`), it prints a
// ready-to-use TypeScript module to stdout.  Redirect the output to a dated
// data file and check it in.

function generateBoothTsCode(
  svgUrl: string,
  booths: Booth[],
  sourceName: string,
): string {
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const boothsJson = JSON.stringify(booths, null, 2);
  return `\
// Auto-generated by extract-hamvention-svgbooth-to-booth.ts on ${date}
// Source: ${sourceName}
// Do not edit by hand — re-run the tool to regenerate.

import type { Booth } from "@/types/conference";

export const mapBooths: [string, Booth[]] = [
  "${svgUrl}",
  ${boothsJson} as Booth[],
];
`;
}

// Detect whether this module is the direct entry point.
// Compare the pathname of import.meta.url (e.g. /path/to/file.ts) against
// process.argv[1] (the script path supplied by Node.js / tsx).
// Using new URL() instead of fileURLToPath avoids a node:url dependency that
// breaks when this module is bundled for the browser.
const isMain =
  typeof process !== "undefined" &&
  Array.isArray(process.argv) &&
  process.argv.length > 1 &&
  new URL(import.meta.url).pathname === process.argv[1];

if (isMain) {
  const booths = convertSvgBoothsToBooth(
    HAMVENTION_2026_BUILDING_1_MAXIM_BOOTHS,
    "building-1",
  );
  const code = generateBoothTsCode(
    SVG_URL,
    booths,
    "hamvention-2026-building-1-maxim.svg / HAMVENTION_2026_BUILDING_1_MAXIM_BOOTHS",
  );
  process.stdout.write(code);
}
